# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RSToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '4.4.0'
  pod 'RxCocoa',    '4.4.0'
  # Pods for RSToDo

end
